
require '技能.英雄技能.暴击'
require '技能.英雄技能.粉碎'
require '技能.英雄技能.重击'
require '技能.英雄技能.闪电手'
require '技能.英雄技能.硬化皮肤'
require '技能.英雄技能.闪避'
require '技能.英雄技能.望远镜'

require '技能.英雄技能.弹射'
require '技能.英雄技能.法术强化'
require '技能.英雄技能.召唤强化'
require '技能.英雄技能.贪婪者的心愿'
require '技能.英雄技能.财富'
require '技能.英雄技能.缠绕'
require '技能.英雄技能.风暴锤子'
require '技能.英雄技能.击地'
require '技能.英雄技能.践踏'
require '技能.英雄技能.穿刺'
require '技能.英雄技能.时间静止'
require '技能.英雄技能.妖刀'
require '技能.英雄技能.静止陷阱'

-- require '技能.英雄技能.荆棘光环'
-- require '技能.英雄技能.强击光环'
-- require '技能.英雄技能.辉煌光环'
-- require '技能.英雄技能.专注光环'
-- require '技能.英雄技能.耐力光环'
-- require '技能.英雄技能.战鼓光环'
-- require '技能.英雄技能.吸血光环'
-- require '技能.英雄技能.寻宝光环'
-- require '技能.英雄技能.财源滚滚'
-- require '技能.英雄技能.冰冷核心'
-- require '技能.英雄技能.魔王降临'
-- require '技能.英雄技能.攻速光环'

require '技能.英雄技能.流星'
require '技能.英雄技能.暴雪'
require '技能.英雄技能.火焰呼吸'
require '技能.英雄技能.死亡之指'
require '技能.英雄技能.连锁闪电'
require '技能.英雄技能.炽热光辉'
require '技能.英雄技能.死亡脉冲'
require '技能.英雄技能.痛苦尖叫'
require '技能.英雄技能.光明契约'
require '技能.英雄技能.摔破罐子'
require '技能.英雄技能.刀刃旋风'
require '技能.英雄技能.激流'
require '技能.英雄技能.黑暗契约'
require '技能.英雄技能.死亡飞镖'
require '技能.英雄技能.狂猛'
require '技能.英雄技能.属性转换'
require '技能.英雄技能.献祭'
require '技能.英雄技能.振动波'
require '技能.英雄技能.群体治疗'
require '技能.英雄技能.圣光'
require '技能.英雄技能.治疗守卫'
require '技能.英雄技能.冰甲'
require '技能.英雄技能.心灵之火'
require '技能.英雄技能.闪电手'
require '技能.英雄技能.愤怒'
require '技能.英雄技能.爱屋及乌'
require '技能.英雄技能.妙手空空'
require '技能.英雄技能.自然之力'
require '技能.英雄技能.水元素'
require '技能.英雄技能.影子'
require '技能.英雄技能.狼'
require '技能.英雄技能.地狱火'
require '技能.英雄技能.凤凰'
require '技能.英雄技能.F4战斗机'
require '技能.英雄技能.战鹰'
require '技能.英雄技能.硬币机器'
require '技能.英雄技能.张全蛋'
require '技能.英雄技能.属性转换'


require '技能.英雄技能.阳光枪'
require '技能.英雄技能.火焰雨'
require '技能.英雄技能.巨浪'
require '技能.英雄技能.飞焰'
require '技能.英雄技能.炎爆术'
require '技能.英雄技能.光子灵枪'
require '技能.英雄技能.闪电链'
require '技能.英雄技能.暴风雪'

require '技能.英雄技能.万箭齐发'
require '技能.英雄技能.回旋刃'
require '技能.英雄技能.交叉闪电'
require '技能.英雄技能.御甲'
require '技能.英雄技能.绿野之矛'
require '技能.英雄技能.风暴之力'


require '技能.英雄技能.神圣护甲'
require '技能.英雄技能.疾步风'
