require '物品.消耗品.生命药水'
require '物品.消耗品.魔法药水'
require '物品.消耗品.吞噬丹'
require '物品.消耗品.随机技能书'
require '物品.消耗品.新手礼包'
require '物品.消耗品.召唤boss'
require '物品.消耗品.召唤练功怪'

require '物品.消耗品.恶魔果实'
require '物品.消耗品.抽奖券'
