require '平台.道具.天使之光'
require '平台.道具.齐天大圣'
require '平台.道具.金币礼包'
require '平台.道具.木材礼包'
require '平台.道具.双倍积分卡'
require '平台.道具.天空的宝藏会员'
require '平台.道具.小翅膀'
require '平台.道具.杰克'
require '平台.道具.后羿'
require '平台.道具.影歌'
require '平台.道具.王昭君'
require '平台.道具.大天使加百列'

require '平台.道具.寻宝小达人'
require '平台.道具.战斗机器'
require '平台.道具.金币多多'
require '平台.道具.穆拉丁'
require '平台.道具.黑魔导'

require '平台.道具.永久超级赞助'
require '平台.道具.魔龙之心'
